"""
Textile Core Fabric Package.
Organized into 5 functional domains: orchestration, security, telemetry, execution, and definitions.
"""

from textile.core.definitions import (
    LayerTier,
    PolicyViolationError,
    StrandNotFoundError,
    TextileError,
    YarnManifest,
    YarnNotFoundError,
    detects_native_ffi,
    get_layer_info,
)
from textile.core.execution import (
    CapabilityTier,
    EventOptions,
    InvokerConfig,
    Strand,
    StrandConfig,
    Weft,
    Yarn,
    strand,
    validate_strand_arguments,
    weft,
)
from textile.core.orchestration import (
    Loom,
    Skein,
    core_fabric_yarn,
    create_twill_server,
    loom,
    run_twill,
    skein,
)
from textile.core.security import (
    AccessBoundaryError,
    OTPChallengeRequiredError,
    OTPManager,
    PendingOTP,
    ScopedPath,
    SessionProcessGuard,
    global_otp_manager,
    verify_security_policy,
)
from textile.core.telemetry import (
    CoreTapestry,
    ElasticEngine,
    EventFrame,
    EventUrgency,
    SensoryTapestry,
    core_tapestry,
    elastic,
    sensory_tapestry,
)

__all__ = [
    "AccessBoundaryError",
    "CapabilityTier",
    "CoreTapestry",
    "ElasticEngine",
    "EventFrame",
    "EventOptions",
    "EventUrgency",
    "InvokerConfig",
    "LayerTier",
    "Loom",
    "OTPChallengeRequiredError",
    "OTPManager",
    "PendingOTP",
    "PolicyViolationError",
    "ScopedPath",
    "SensoryTapestry",
    "SessionProcessGuard",
    "Skein",
    "Strand",
    "StrandConfig",
    "StrandNotFoundError",
    "TextileError",
    "Weft",
    "Yarn",
    "YarnManifest",
    "YarnNotFoundError",
    "core_fabric_yarn",
    "core_tapestry",
    "create_twill_server",
    "detects_native_ffi",
    "elastic",
    "get_layer_info",
    "global_otp_manager",
    "loom",
    "run_twill",
    "sensory_tapestry",
    "skein",
    "strand",
    "validate_strand_arguments",
    "verify_security_policy",
    "weft",
]
