[yarn]
name = "dbus_system"
publisher = "textile"
version = "1.0.0"
manifest_version = 1
layer = 50
description = "D-Bus system and session bus inspection and call dispatching"

[dependencies]
python = ["sdbus"]
system = []
