[yarn]
name = "journal"
publisher = "textile"
version = "1.0.0"
layer = 50
description = "Systemd journald logs inspection and query tool"

[dependencies]
python = ["systemd-python"]
system = ["journalctl"]
